### PR TITLE
Spanish translation v2

### PR DESCRIPTION
**Pull request by javierfdezg**
Added suggestions and fixed typo

### CODE REVIEW

**Comment by ricardojmendez** [comment]
Partly nitpicking, but I'd say use “patrocinadores” instead of “espónsors”. Never heard the "espónsors" Anglicism before, so it might be used only in a few countries.

**Comment by SamirTalwar** [comment]
Happy to merge, @javierfdezg, just waiting for agreement (and potentially a change) on that last one.

**Comment by javierfdezg** [comment]
Yes, please wait 😀

I hadn't had the chance to update it.

**Comment by javierfdezg** [comment]
Done! @ricardojmendez I heard it a lot but it makes more sense to use 'patrocinador'.

Thanks!

**Comment by SamirTalwar** [comment]
I wanted to let you know that a number of people on Twitter have also read through this and said nothing more than that it looks great. So thank you for your efforts, everyone. 😄

**Comment by javierfdezg** [comment]
Cool!

**Pull request merged**
