### PR TITLE
Finnish translation

### PR DESCRIPTION
**Pull request by tommijoentakanen**
Renamed the file to index-fi.html

Contents are until the long version (work in progress with @rinkkasatiainen)

### CODE REVIEW

**Comment by SamirTalwar** [comment]
Any update on this, @tommijoentakanen?

**Comment by jukecraft** [comment]
I've asked a professional translator to have a try and have an alternative PR:
https://github.com/SamirTalwar/communitycodeofconduct.com/pull/13

@tommijoentakanen @rinkkasatiainen can you give your review?

**Comment by rinkkasatiainen** [comment]
This very good translation. Way better than I could've done myself.

**Comment by jukecraft** [comment]
I propose to close this one since the other one has been merged :)

**Pull request closed without merging**
