### PR TITLE
Add Japanese version.

### PR DESCRIPTION
**Pull request by atsushieno**

### CODE REVIEW

**Comment by SamirTalwar** [comment]
Thank you very much! I need to find someone else to review this, and then we're good to go.

**Comment by georgberky** [comment]
@atsushieno さんへ：行動規範を日本語に訳してくれてありがとうございました！日本語のネーティブスピーカーではありませんので、どうぞ宜しくお願いします。

I've read the Japanese translation in the pull request for the community code of conduct.

I'm not a native speaker of Japanese, but having lived in Japan for a year it looks like a good translation to me. The language is formal and to me feels like it matches the style of the English version - maybe even a bit more formal.

In "The less quick version", Eno-san added the "(or lack thereof)" back in after "religion", probably as a copy from the part above.

The word 司法警察組織 (shihou keisatsu soshiki) for "local law enforcement" literally translates to "organization (soshiki) of justice administration  (shihou) and police (keisatsu)". I simply don't know that word. It might be specialized legal language judging from the combination of the words or just the best possible translation in Japanese to bring across "the local equivalent of justice and police".

HTH

**Comment by SamirTalwar** [comment]
Gonna merge this. Any further changes (either along the lines of @georgberky's or not), feel free to raise more PRs.

Thanks @atsushieno!

**Comment by SamirTalwar** [comment]
[It's up!](https://jp.communitycodeofconduct.com/)

**Comment by atsushieno** [comment]
Ahh, sorry I was taking slow action. Thanks @SamirTalwar , I hope it works, I had some people already reviewing at https://gist.github.com/atsushieno/b6fa985354b5583f027d10618f6d1438 so hopefully it's about right.

**Comment by SamirTalwar** [comment]
I'm sure it is. I just like to have these things checked because, as I'm sure you've figured, I can't read a word of it myself. ;-)

**Pull request merged**
