### PR TITLE
improvements for turkish translation.

### PR DESCRIPTION
**Pull request by veysiertekin**
Hi @SamirTalwar ,
I couldn't review the previous merge request because of one of my freelance project, so i made a few minor changes for turkish translation 👍

### CODE REVIEW

**Comment by SamirTalwar** [comment]
Thanks!

@erkanerol, @volkantufekci, @fsonmezay, could any of you take a look at this please?

**Comment by erkanerol** [comment]
@veysiertekin  Thanks for your help.

I think the title change is necessary. 
Some changes are optional.
Some changes are not better than the existing version.  e.g. "yerel kanun güçleri","ceza uygulanabilir"

Note: I have used http://tr.confcodeofconduct.com/ in translation.

**Comment by veysiertekin** [comment]
You are right about optional changes, that's why i reverted all the changes except title. This is easy to be a right PR, i think :)

**Comment by erkanerol** [comment]
@SamirTalwar  @veysiertekin Did you realize there is a problem in the current versions of all html files? the html tags are not closed properly :)  

@veysiertekin Could you check and fix? Could you commit those changes in this pull request?

**Comment by SamirTalwar** [comment]
@erkanerol: Good point. It's the same in the original [confcodeofconduct.com](https://github.com/confcodeofconduct/confcodeofconduct.com) repository, but we can fix it on our end.

Let's do it as a separate PR.

**Pull request merged**
